version: "3.8"

services:

  drupal:
    image: drupal:9.0
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites

  psql_drupal:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: example

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
